#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvdpau
Version  : 1.1.1
Release  : 1
URL      : https://gitlab.freedesktop.org/vdpau/libvdpau/uploads/5635163f040f2eea59b66d0181cf664b/libvdpau-1.1.1.tar.bz2
Source0  : https://gitlab.freedesktop.org/vdpau/libvdpau/uploads/5635163f040f2eea59b66d0181cf664b/libvdpau-1.1.1.tar.bz2
Summary  : The Video Decode and Presentation API for UNIX
Group    : Development/Tools
License  : MIT
Requires: libvdpau-lib = %{version}-%{release}
Requires: libvdpau-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)

%description


%package dev
Summary: dev components for the libvdpau package.
Group: Development
Requires: libvdpau-lib = %{version}-%{release}
Provides: libvdpau-devel = %{version}-%{release}

%description dev
dev components for the libvdpau package.


%package doc
Summary: doc components for the libvdpau package.
Group: Documentation

%description doc
doc components for the libvdpau package.


%package lib
Summary: lib components for the libvdpau package.
Group: Libraries
Requires: libvdpau-license = %{version}-%{release}

%description lib
lib components for the libvdpau package.


%package license
Summary: license components for the libvdpau package.
Group: Default

%description license
license components for the libvdpau package.


%prep
%setup -q -n libvdpau-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546251385
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1546251385
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libvdpau
cp COPYING %{buildroot}/usr/share/package-licenses/libvdpau/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/vdpau/vdpau.h
/usr/include/vdpau/vdpau_x11.h
/usr/lib64/libvdpau.so
/usr/lib64/pkgconfig/vdpau.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libvdpau/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvdpau.so.1
/usr/lib64/libvdpau.so.1.0.0
/usr/lib64/vdpau/libvdpau_trace.so
/usr/lib64/vdpau/libvdpau_trace.so.1
/usr/lib64/vdpau/libvdpau_trace.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libvdpau/COPYING
